-- liquibase formatted sql

-- changeset ara:1665752039468-2
--CREATE TABLE "roles2" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "email" VARCHAR(20), CONSTRAINT "roles2_pkey" PRIMARY KEY ("id"));
